spring:
  application:
    name: processing-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          max-retries: 3
          initial-interval: 3s # Wait time after first failure
          multiplier: 2.0 # Increment wait time by 2x after each failure
          max-interval: 10s

  main:
    web-application-type: none